name: "it-tools"
version: "2024.10.22-7ca5933"
image: corentinth/it-tools
slug: it-tools
description: "Collection of handy online tools for developers, with great UX as a web app."
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 8088